#!/bin/sh
# pre-commit hook
#
# Ensures that PENDING.md files exist before commit.

echo "--- Running pre-commit hook ---"
python scripts/ensure_pending.py
if [ $? -ne 0 ]; then
    echo "[Error] Pre-commit checks failed. Aborting commit."
    exit 1
fi
echo "--- Pre-commit hook finished ---"
exit 0